### ISSUE TITLE
Rename the repository into feedback

### ISSUE THREAD

**Issue by bertux** [artheranet/feedack#1]
The title of README is feedback but the name of the repository is feedack.

**Comment by artheraone** [comment]
Not sure I understand the issue

**Comment by ygd58** [comment]
hello I like and follow your project and I would like to collaborate I am a core node team member we have participated in many projects and we are an experienced team for validators and verifiers and we have projects in collaboration with opside and goracle network cascadia and many team members are involved in important projects we also have a core node community I will send you detailed information about core node github and team members I think you might like to know us thanks 
https://www.corenode.team/
https://twitter.com/corenodeHQ
https://github.com/core-node-team 
https://discord.gg/VJekmRgdJw
 CORE NODE TEAM BRIEFING
Socrates
Core node team leader project partnership collaborator and team member responsible for preparing the installation repos of the projects, setting up the node, resolving bugs in the nodes and responsible for security and communication with the projects
King
Core node team leader project partnership collaborator and team member responsible for core node community growth and communication with projects
Buraysandro
Core node team leader project partnership collaborator project review project researcher team member responsible for communication with projects
Core Node Dev Team

@ahmkah
Data center specialist. The person who carries out server procurement, performance monitoring and improvement activities. Communicates with server companies.

Linaril
Network specialist responsible for cyber security in the company he works for. Team member responsible for security in all the work of the core node team

Penta
Academic Linux expert, advanced python knowledge. Team member responsible for performance monitoring and improvement of nodes and other software, preparing various software for monitoring, writing tools as needed.

**Comment by julienbrg** [comment]
> Not sure I understand the issue

I think it's just a typo in the repo name, there's a 'b' missing.

**Comment by bertux** [comment]
this name could be read as FeedAck to acknowledge the feed of comments sent here so need to change it.
